### ISSUE TITLE
weekview layout constraints

### ISSUE THREAD

**Issue by ezmegy** [Quivr/iOS-Week-View#2]
Hi,

I'm not sure how I should set the weekview's constraints:
- If I set my weekview to occupy the full screen (center it and size == parent view's size), the top bar (with the day labels) disappears, [see screenshot](https://drive.google.com/open?id=0B5UFlCWAEL50Q3pTWGliOXZNSnc).
- If I set the weekview's height to a percentage less than 1 (say 0.9) of the parent's size, than there will be a small gap rendered on top: [see screenshot](https://drive.google.com/open?id=0B5UFlCWAEL50TUlsa2NWZUtrVE0). 

Is the top bar's size fixed maybe? How to set it to support different screen sizes?

Cheers

**Comment by reilem** [comment]
This is due to the fact that your the default subview of a viewcontroller extends underneath the navigation bar. I would recommend not using the default subview in this case and either attaching the weekView to the viewController directly in the storyboard and using the graphical interface to add constraints (see image).
<img width="769" alt="screen shot 2017-08-15 at 16 20 36" src="https://user-images.githubusercontent.com/11155505/29319911-ed2a5764-81d5-11e7-8f43-642a24156cda.png">
Or you could do it programatically and add constraints to your weekView, but this is quite tricky to do programmatically, you can find out how to [here](https://stackoverflow.com/questions/26180822/swift-adding-constraints-programmatically).

**Comment by ezmegy** [comment]
Thanks, it did the trick!
