### ISSUE TITLE
switching between number of days visible

### ISSUE THREAD

**Issue by ezmegy** [Quivr/iOS-Week-View#6]
Hi,

I have my weekWiew that is set up to display a whole week first and then later I try to change the number of days visible. I do this: 

`weekView.visibleDaysInLandscapeMode = 1`
`weekView.visibleDaysInPortraitMode = 1`

and WeekView.swift gives me an index out of range error on line 393

But only with 1, and not for example with 3 or 4.

What am I missing, is this maybe not the intended way to switch the number of days that are shown?

**Comment by reilem** [comment]
Oh dear! I seemed to have made a very basic programming mistake. It was a piece of code I had written for a "just in case" situation and hadn't had the change to properly test it. I was iterating over a value and instead of simply removing the first element from the list I was removing the element at the index I was using to iterate. Release 0.9.1 hopefully should have the fix. :) Thanks so much for bringing this to light!

**Comment by ezmegy** [comment]
That's a quick&easy fix then, great! :)
Cheers
